# Generated by Django 4.0.3 on 2022-11-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='email',
            field=models.EmailField(default='manager@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='location',
            field=models.CharField(default='mumbai', max_length=30),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='project',
            field=models.CharField(choices=[('l&a', 'L&A'), ('claims', 'CLAIMS'), ('nonclaims', 'NONCLAIMS'), ('ba', 'BA'), ('tester', 'TESTER')], default='L&A', max_length=30),
        ),
    ]
